name: Build

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  ubuntu-2004:
    name: Ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
    - name: Configure
      run: cmake -Bbuild .
    - name: Build
      run: cmake --build build -j 2
